examples/typescript/index.tsx
types/index.d.ts

Motivation: 
When creating mocks especially when we are mocking `react hooks`(or to be precise hook return values) we don't need every field in our test
Here is an one of examples that i was implementing earlier , from project context in my test i only needed `projectId` and `projectName`, but still i needed to pass all other fields. I know i could make `data` field partial as well but here how ugly typescript code comes in.
before:
```
injectable<() => Partial<ReturnType<typeof useProjectContext>>>(useProjectContext, () => ({
data: {
projectId: 10001,
projectName: 'TM-1',
projectType: 'business',
isProjectAdmin: true,
projectKey: 'TM-1',
projectUuid: 'uuid',
simplified: false,
isProjectArchived: null,
},
})),
```
after:
```
injectable(useProjectContext, () => ({
data: {
projectId: 10001, …
```

update implementation of injectable

---

types/index.d.ts

Make type infer faster and prevent some issues with partial of circular types by providing a plain identity overload
Thanks @theKashey

Add simple type identity overload for injectable

---

package-lock.json
package.json
src/react/__tests__/common.js
src/react/__tests__/integration-rtl.test.js
src/react/__tests__/integration-rtr.test.js
src/react/consumer.js

Seems like `react-test-renderer` uses the "alternative" renderer code path to share current context values. So we check them first if a second renderer is running, falling back to primary renderer if not
Closes #62

Support react-test-renderer

---

README.md
examples/global/__tests__/index.test.ts
examples/global/index.ts
src/index.js
src/index.js.flow
src/react/__tests__/common.js
src/react/__tests__/global.test.js
src/react/__tests__/types.flow.js
src/react/consumer.js
src/react/context.js
src/react/global.js
types/index.d.ts
types/test.tsx

New API to use `di` outside of React.
```js
import { runWithDi } from 'react-magnetic-di'
const myDependencyDi = injectable(myDependency, () => 'mock')
runWithDi(() => myFunction(), [myDependencyDi]);
```

Add runWithDi feature

---

README.md
src/index.js
src/index.js.flow
src/react/__tests__/stats.test.js
src/react/__tests__/types.flow.js
src/react/global.js
src/react/provider.js
src/react/stats.js
types/index.d.ts
types/test.tsx

Adds a new `stats` API that allows reporting of unused/missing injectables.
```js
stats.unused().forEach((entry) => {
// get the unused injectable
console.log('Unused', entry.get());
// use the helper to get more meaningful errors
throw entry.error();
});
stats.missing().forEach((entry) => {
// get the missing dependency
console.log('Missing', entry.get());
// use the helper to get more meaningful errors
throw entry.error();
});
stats.reset();
```
Closes #69 .

Add stats API

---

src/eslint/rules/__tests__/exaustive-inject.test.js
src/eslint/rules/exhaustive-inject.js

Recursive components current report as errors, but when auto-fixed don't work correctly.
This commit keeps track of the current component/function name stack and ignores adding any of them into the `di` call statement. Stacking addresses the following use cases:
```
function MenuRenderer({ menu }) {
const renderSubMenu = (subMenu) => <MenuRenderer menu={subMenu} key={subMenu.id} />;
return (
<div>
{menu.name}
{menu.subMenus.map(renderSubMenu)}
</div>
);
}
```
Here we should see a stack going: `[] => [MenuRenderer] => [MenuRenderer, renderSubMenu] => [MenuRenderer] => []`.
I can't think of a case where any member of these stacks should be added to the dependencies list, although there's no control of what is getting tracked in the stack (can be a component, nested function, renderProp, …

Fix eslint rule for recursive components

---

README.md
src/index.js.flow
src/react/__tests__/stats.test.js
src/react/__tests__/types.flow.js
src/react/global.js
src/react/provider.js
src/react/stats.js
src/react/utils.js
types/index.d.ts
types/test.tsx

Add a configuration option to `injectable` to allow custom `displayName` and `track`

Allow injectable to skip tracking

---

examples/typescript/components/__tests__/input.test.tsx
src/react/__tests__/global.test.js
src/react/__tests__/provider.test.js
src/react/global.js
src/react/provider.js
src/react/utils.js
types/index.d.ts
types/test.tsx

Turns out we did not check for the right things to be used as injectable 🤦 
- added runtime error
- added TS opaque type for injectable so we can have TS complain at the right place

Throw error when providing non injectables

---

src/index.js.flow
src/react/__tests__/stats.test.js
src/react/__tests__/types.flow.js
src/react/stats.js
types/index.d.ts
types/test.tsx

Didn't realise missing functionality runs also in dev mode. Removing for now until needs arise and we find a better way to enable tracking only in testing. Also it was not yet documented so should be fine to quickly patch

Remove stats.missing() API

---

src/eslint/rules/__tests__/no-restricted-injectable.test.js
src/eslint/rules/no-restricted-injectable.js
src/eslint/rules/order.js
src/eslint/utils.js

New ESLint rule to lint against problematic injectables (eg react imports)
```js
'no-restricted-injectable': [
'error', 
{ 
paths: [
{ name: 'react', importNames: ['useState'], message: 'Please extract it and create a dedicated hook.' }
],
}
]
```

Add no-restricted-injectable eslint rule

---

src/babel/__tests__/unit.test.js
src/babel/processor-di.js

Using the same identifier reference breaks CommonJS transformation, we need new identifier instances on every added `di` expression

Ensure break identifier reference

---

README.md
src/react/__tests__/common.js
src/react/__tests__/global.test.js
src/react/__tests__/integration-rtl.test.js
src/react/__tests__/integration-rtr.test.js
src/react/__tests__/provider.test.js
src/react/__tests__/stats.test.js
src/react/global.js
src/react/injectable.js
src/react/provider.js
src/react/stats.js
src/react/utils.js

This PR adds a new prop to `DiProvider` and a config to `injectable`: `global: bool`.
It enables declared replacements to be available in the global scope (and so outside the render context) until the component gets unmounted.

Add provider global behaviour

---

examples/.babelrc.js
examples/flow/components/input.js
examples/flow/components/label.js
examples/flow/components/section.js
examples/global/index.ts
examples/typescript/components/input.tsx
examples/typescript/components/label.tsx
examples/typescript/components/section.tsx
src/eslint/rules/no-extraneous.js
src/index.js
src/react/__tests__/provider.test.js
src/react/provider.js

Fix provider global clenup on error

---

src/babel/__tests__/unit.test.js
src/babel/processor-di.js

Consider the following code:
```tsx
function token(path) {
let token = tokens[path];
}
```
right now it will be converted into
```tsx
function token(path, fallback) {
const [_tokens] = (0, _reactMagneticDi.di)([_tokenNames.default], token);
let token = _tokens[path];
}
```
However, due to `let token` we will face the temporal dead zone or "cannot access token before initialization"
----
This PR just handles this moment by removing scope when such case is detected.

fix: handle temporal deadzone for local variables shadowing parent function

---

src/babel/__tests__/unit.test.js
src/babel/index.js
src/babel/processor-di.js

If computed properties are using a dependency, the scope rename would impact them too even if it should not (I've opened an issue on Babel side too https://github.com/babel/babel/issues/16751 as I think it is somewhat unexpected)
So we added a special condition that checks for computed properties and ignores the immediate scope and reverts the renamed identifier.
Closes #92

Fix computed properties being renamed

---

src/babel/__tests__/unit.test.js
src/babel/index.js

Sometimes it might happen that consumers mistakenly add the plugin twice (see #94). Currently we blow up as we detect a wrong `di` use, but instead we could just skip processing the file and silently continue.

Skip processing if di already processed

---

README.md
babel.config.js
src/babel/__tests__/unit.test.js
src/babel/index.js
src/babel/processor-di.js
src/babel/processor-inj.js
src/babel/utils.js
src/index.js.flow
types/index.d.ts

New babel options:
```js
// Mock injectables imports to improve test performance
// Currently supports only jest
mockModules: 'jest',
// Automatically mock injectables imports (needs mockModules set)
// For instance mock all injectables imports that are 1st party @app/foo
defaultMockedModules: ['@app/'],
```
The former, together with a new `injectable` option called `module`, allows the module of the imported variable to be mocked by jest (via `jest.mock`).
```js
const modalDi = injectable(Modal, () => null, { module: true });
```
The latter, is an experimental auto-mock behaviour, where we can automatically add jest.mock calls for all packages with an injectable defined. Should be useful to test the impact at scale (but lots of tests might fail)

Allow module mocking via jest.mock

---

README.md
src/babel/__tests__/unit.test.js
src/babel/processor-di.js
src/react/__tests__/common.js
src/react/__tests__/consumer.test.js
src/react/__tests__/global.test.js
src/react/__tests__/provider.test.js
src/react/consumer.js
src/react/global.js
src/react/injectable.js
src/react/provider.js
src/react/utils.js

- instead of creating an array for the dependencies, use plain arguments as `fn.call` does, reducing memory and processing time
- directly mutate the rest arguments to avoid creating new arrays 
- check global replacements size to avoid any processing if none is set 
- use `WeakSet` to check if targets matches

Improve performance via rest argument and short circuit

---

src/react/__tests__/stats.test.js
src/react/stats.js

Not sure when this regression happened, but in node 20 setting `cause` to `null` on the injectable object also makes the error's `cause` property to become `null`. Unless there is something that I'm not seeing, could not find a way to retain the value (local assignments, `structuredClone`, explicit stack reference, ...). 
Given we want to keep the error only when injectables are not used, it was easy enough to move the cleanup when we `track` the usage so it is persisted only otherwise.

Fix cause bicoming null if reset straight away

---

src/react/global.js

In very short - `.finally` will create another promise and if the test function did fail - that would be another rejected promise, and the unhandled one. That would lead test to the failure somewhere afterEach
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
> unlike Promise.reject(3).then(() => {}, () => 88), which returns a promise eventually fulfilled with the value 88, Promise.reject(3).finally(() => 88) returns a promise eventually rejected with the reason 3.

fix: dont use promise.finally as it creates new unhandled promise rejection
